name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v3.3.0
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install, lint, test, and build
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true
