name: Build and Deploy
on:
  push:
      branches:
        - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v3.5.1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1

      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CLEAN: true
